### ISSUE TITLE
ProductsByStablishmentActivity

### ISSUE THREAD

**Issue by rialdana** [rialdana/supermercado-app-utec#4]
- [x] Crear activity y layout
- [x] Definir entity para producto
- [x] Mostrar listado de productos

Fragment para ingresar productos
- [x] Crear fragment para ingresar productos 
- [x] Mostrar las categorias disponibles (desde room) en un spinner
- [x] Almacenar productos nuevos
- [x] Validar que los campos no esten vacios antes de guardar

**Comment by alexis-92** [comment]
Se termino pero no pude hacer q cargue de nuevo el producto agregado, hay q entrar y salir del Activity
